name: defects
channels:
  - defaults
  - conda-forge
  - anaconda
  - glotzer
dependencies:
  # Running Simulations
  - python=3.6
  - numpy=1.16.*
  - malramsay::sdrun=0.8.1
  - malramsay::sdanalysis=0.10.0
  - malramsay::experi=0.3.4
  # Dev tools
  - pytest=5.0.*
  - mypy=0.740
  - black=19.10b0
  - pip=19.1
  - isort=4.3.21
  - pylint=2.3.1
  - jupytext=1.2.1
  - flake8=3.7.7
  - flake8-docstrings=1.3.1
  # Interactive analysis
  - scikit-learn=0.21.*
  - joblib=0.13.2
  - ipykernel=5.1.1
  - ipywidgets
  - altair=3.2.*
  - nbdime=1.0.*
  - matplotlib=3.1.*
  - selenium
  - jupyterlab=1.0.*
  - geckodriver=0.24.0
  - phantomjs
  # Reports
  - pandoc
  - pandoc-crossref
  - cairosvg
